export interface Contact {
  [key: string]: any
  Id: string
  SFDCId: string
  ContactId: string
  PID: string
  CustomerCode: string
  ProjectCode: string
  Type: string
  file1: string
  file2: string
  file3: string
  file4: string
  file5: string
  file6: string
  file7: string
  file8: string
  file9: string
  file10: string
  file11: string
  file12: string
  file13: string
  file14: string
  file15: string
  file16: string
  file17: string
  file18: string
  file19: string
  file20: string
  file21: string
  file22: string
  file23: string
  file24: string
  file25: string
  file26: string
  file27: string
  file28: string
  file29: string
  file30: string
  file31: string
  file32: string
  file33: string
  file34: string
  file35: string
}
